# Generated by Django 2.1.2 on 2018-10-03 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short keyword for classifying things.', max_length=60, unique=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notes.Category')),
            ],
        ),
        migrations.CreateModel(
            name='TextNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='This is a short descriptive title for the note.', max_length=80)),
                ('text', models.TextField(help_text='This is the contents of the note')),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notes.Category')),
            ],
        ),
        migrations.AddIndex(
            model_name='textnote',
            index=models.Index(fields=['category'], name='notes_textn_categor_8f5293_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='textnote',
            unique_together={('title', 'createdOn')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='notes_categ_parent__ea97f3_idx'),
        ),
    ]
