# Generated by Django 2.1.2 on 2018-10-03 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnote',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='notes.Category'),
        ),
        migrations.AlterField(
            model_name='textnote',
            name='text',
            field=models.TextField(blank=True, help_text='This is the contents of the note'),
        ),
    ]
